spring:
  application:
    name: ks-it-school
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
      format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://143.198.93.97:5434/ks_it_school}
    username: ${SPRING_DATASOURCE_USERNAME:menghor}
    password: ${SPRING_DATASOURCE_PASSWORD:Hour1819}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connectionTimeout: 99930000
      idleTimeout: 99600000
      maxLifetime: 991800000

  mvc:
    static-path-pattern: /static/**
    web:
      resources:
        static-locations: classpath:/static/,classpath:/public/

server:
  port: ${APP_PORT:8080}

jwt:
  secret:
    key: da2bd42bef8f9f957d647ed13571d35b59c7055fb723eacdb05154878da17d77d3180385fc232cab38bded0fc7dbda0d439cc275e91164ade266d64d50633bc7
  expiration-min: 1440000000000

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    enabled: true
    url: /v3/api-docs
    config-url: /v3/api-docs/swagger-config
  api-docs:
    path: /v3/api-docs
    enabled: true
  packagesToScan: com.menghor.ksit